# Generated by Django 4.2 on 2024-08-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(choices=[('alimentos', 'Alimentos'), ('transporte', 'Transporte'), ('vivienda', 'Vivienda'), ('entretenimiento', 'Entretenimiento'), ('salud', 'Salud'), ('educacion', 'Educación'), ('varios', 'Varios')], max_length=100),
        ),
    ]
