# Generated by Django 4.2 on 2024-08-04 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_historialmensual'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistorialMensual',
        ),
    ]
