# Generated by Django 4.2 on 2024-08-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0005_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
