# Generated by Django 4.2 on 2024-08-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0008_alter_avatar_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='medio_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('debito', 'Débito'), ('credito', 'Crédito'), ('transferencia', 'Transferencia')], default='efectivo', max_length=100),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='categoria',
            field=models.CharField(choices=[('sueldo', 'Sueldo'), ('otros', 'Otros')], default='otros', max_length=100),
        ),
    ]
